import os
import subprocess
import glob
import shutil
import csv
import sys
import math
import random
import time
from datetime import datetime

# ================= Configuration =================
# 输出到独立的文件，避免混淆，后续你可以把两个csv手动合并
REPORT_FILE = "benchmark_results_large.csv"

# 基础配置
DTYPES = ["float16", "float32"]
P_VALUES = ["1.0", "2.0", "inf", "3.0"]
DATA_RANGE = "S"

# 约束条件 (放宽限制以允许 5000x40000)
MAX_N = 6000          # 稍微放宽一点
MAX_M = 200000
MAX_COMPLEXITY = 1.1e12  # N^2 * M, 允许稍微超过 1e12 一点点

# ================= Utils =================
def clean_logs():
    """Clean old OP* directories"""
    for item in glob.glob("OP*"):
        if os.path.isdir(item):
            shutil.rmtree(item)

def update_config(n, m, p, dtype):
    """Rewrite config.txt"""
    config_content = f"""# Auto-generated by benchmark script
N={n}
M={m}
p={p}
data_type={dtype}
data_range={DATA_RANGE}
"""
    with open("config.txt", "w") as f:
        f.write(config_content)

def get_latest_profile_dir():
    """Get the latest generated OP directory"""
    dirs = glob.glob("OP*")
    if not dirs:
        return None
    dirs.sort(key=os.path.getmtime, reverse=True)
    return dirs[0]

def parse_duration(log_dir):
    """Find 'Task Duration(us)' for Pdist operator"""
    csv_path = None
    for root, dirs, files in os.walk(log_dir):
        if "OpBasicInfo.csv" in files:
            csv_path = os.path.join(root, "OpBasicInfo.csv")
            break
    
    if not csv_path:
        return None

    try:
        with open(csv_path, 'r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            if reader.fieldnames:
                reader.fieldnames = [name.strip() for name in reader.fieldnames]
            for row in reader:
                op_name = row.get("Op Name", "")
                if "Pdist" in op_name:
                    return float(row.get("Task Duration(us)", 0))
    except Exception:
        pass
    return None

# ================= Test Case Generation (Large Scale Focus) =================
def get_large_test_cases():
    cases = []
    
    # 定义我们要补充的大比例射线
    # (Group Name, N_Ratio, M_Ratio)
    rays = [
        ("C_Scale_1_1", 1.0, 1.0),   # 补充 3000 -> 5000
        ("C_Scale_1_4", 1.0, 4.0),   # 补充 3000 -> 5000 (M -> 20000)
        ("C_Scale_4_1", 4.0, 1.0),   # 补充 N -> 5000 (M -> 1250)
        ("C_Scale_1_8", 1.0, 8.0),   # NEW! 专门覆盖 5000 x 40000
    ]
    
    # 基础 Scale：从 2500 开始，一直推到 5500
    # 我们生成 8 个关键点，重点覆盖 3000, 4000, 5000 附近
    # [2500, 2928, 3428, 4014, 4700, 5500] 类似的对数分布
    import numpy as np
    base_scales = np.geomspace(2500, 5200, num=7, dtype=int).tolist()
    
    # 额外强制加入 5000 这个整数点
    if 5000 not in base_scales:
        base_scales.append(5000)
    base_scales.sort()

    for group_name, r_n, r_m in rays:
        for scale in base_scales:
            # 计算 N 和 M
            n = int(scale * r_n)
            m = int(scale * r_m)
            
            # 加入一点点 Jitter (随机扰动)，避免全是整百整千
            if n > 100: n += random.randint(-3, 3)
            if m > 100: m += random.randint(-3, 3)
            
            # 过滤掉已经跑过的小 Case (N < 2800 且 M < 10000 的大概率跑过了)
            # 这里简单起见，只保留比较大的
            # 对于 4:1 的情况，M 很小，所以主要看 N
            if n < 2800 and m < 10000:
                continue

            # Constraints Check
            if n > MAX_N or m > MAX_M:
                continue
            
            # 复杂度检查
            complexity = float(n) ** 2 * float(m)
            if complexity > MAX_COMPLEXITY:
                # 如果超标了，我们尝试缩小一点点以贴近边界，而不是直接丢弃
                # 这样能保证我们测到极限
                factor = (MAX_COMPLEXITY / complexity) ** (1/3) # 粗略缩放
                n = int(n * factor)
                m = int(m * factor)
            
            # 再次检查去重
            if not any(c['n'] == n and c['m'] == m for c in cases):
                cases.append({
                    "group": group_name,
                    "n": n,
                    "m": m
                })

    return cases

# ================= Main Loop =================
def main():
    # 1. Prepare Cases
    shape_cases = get_large_test_cases()
    
    # Expand by Dtype and P values
    full_tasks = []
    for shape in shape_cases:
        for dtype in DTYPES:
            for p in P_VALUES:
                task = shape.copy()
                task['dtype'] = dtype
                task['p'] = p
                full_tasks.append(task)

    total_tasks = len(full_tasks)
    print(f"🚀 Large Scale Benchmark Plan Loaded.")
    print(f"   Focus:         Group C (Proportional Scaling)")
    print(f"   Unique Shapes: {len(shape_cases)}")
    print(f"   Total Runs:    {total_tasks}")
    # 大算子跑得慢，假设每个 2 分钟
    print(f"   Est. Time:     {total_tasks * 2 / 60:.1f} hours (assuming 2min/case)")
    print("-" * 60)

    # 2. Initialize CSV
    file_exists = os.path.isfile(REPORT_FILE)
    with open(REPORT_FILE, 'a', newline='') as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["Timestamp", "Group", "N", "M", "P", "Type", "Duration(us)", "Status"])

    # 3. Execution Loop
    for idx, task in enumerate(full_tasks):
        n = task['n']
        m = task['m']
        p = task['p']
        dtype = task['dtype']
        group = task['group']
        
        prefix = f"[{idx+1}/{total_tasks}]"
        print(f"{prefix} Group:{group:<15} N={n:<5} M={m:<6} P={p:<4} {dtype:<8} ... ", end="", flush=True)
        
        clean_logs()
        update_config(n, m, p, dtype)
        
        status = "OK"
        duration = -1
        
        start_time = time.time()
        try:
            # 环境变量
            env = os.environ.copy()
            # 确保这里是你想要的 NPU 卡号，如果 run.sh 里没改，这里可以强行注入
            env["ASCEND_DEVICE_ID"] = "7" 

            # 大算子容易超时，把 timeout 设长一点 (比如 5 分钟 = 300s)
            subprocess.run(["msprof", "op", "./run.sh"], 
                           capture_output=True, 
                           check=True,
                           timeout=300,
                           env=env) 
            
            log_dir = get_latest_profile_dir()
            if log_dir:
                d = parse_duration(log_dir)
                if d is not None:
                    duration = d
                else:
                    status = "ParseErr"
            else:
                status = "NoLogDir"

        except subprocess.TimeoutExpired:
            status = "Timeout"
            print("TIMEOUT!", end=" ")
        except subprocess.CalledProcessError:
            status = "RunFail"
        except Exception as e:
            status = "Error"
        
        # Write Result Immediately
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(REPORT_FILE, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([timestamp, group, n, m, p, dtype, duration, status])
        
        # Print
        if duration > 0:
            # 转换为 ms 显示更直观
            print(f"Done. {duration/1000:.2f} ms")
        else:
            print(f"Failed ({status}).")

    print(f"\n✅ Large scale tests completed. Results saved to {REPORT_FILE}")

if __name__ == "__main__":
    main()